### ISSUE TITLE
Caused by: java.io.IOException: resource not found on classpath: application.conf

### ISSUE THREAD

**Issue by AndrewKL** [sihil/plambda#3]
I'm running into a bug where the lambda function is unable to find the application.conf file
```
Caused by: com.typesafe.config.ConfigException$IO: application: application.conf: java.io.IOException: resource not found on classpath: application.conf, application.json: java.io.IOException: resource not found on classpath: application.json, application.properties: java.io.IOException: resource not found on classpath: application.properties
at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:236)
at com.typesafe.config.impl.ConfigImpl.parseResourcesAnySyntax(ConfigImpl.java:132)
at com.typesafe.config.ConfigFactory.parseResourcesAnySyntax(ConfigFactory.java:1024)
at com.typesafe.config.ConfigFactory.parseApplicationConfig(ConfigFactory.java:238)
at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:519)
at play.api.Configuration$$anonfun$3.apply(Configuration.scala:73)
at play.api.Configuration$$anonfun$3.apply(Configuration.scala:69)
at scala.Option.getOrElse(Option.scala:121)
at play.api.Configuration$.load(Configuration.scala:69)
... 13 more
Caused by: com.typesafe.config.ConfigException$IO: application.conf: java.io.IOException: resource not found on classpath: application.conf
at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:188)
at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
at com.typesafe.config.impl.Parseable.parse(Parseable.java:152)
at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:185)
... 21 more
Caused by: java.io.IOException: resource not found on classpath: application.conf
at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:735)
at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:710)
at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
... 24 more
```

When I unzip the jar I see the file.

>unzip -l ./path/to./jar

```
     9599  10-02-2018 12:48   bin/acrotesseract.bat
     1619  10-01-2018 14:57   conf/application.conf
      320  10-01-2018 14:57   conf/routes
     6459  10-02-2018 12:34   share/doc/api//index.html
```

**Comment by AndrewKL** [comment]
So I've got a new theory as to whats going on.  While the top level zip package has /conf/application.conf  The inner jars in the /lib/ folder does not.

**Comment by jadedh** [comment]
Hi there, How did you ended up working around this?

**Comment by emupton** [comment]
this issue is old but fyi adding this to the top level of your build.sbt will fix:
```
scriptClasspath += "/app/conf/*"
```
